name: Transfer New Issue to Docs Project

on:
  issues:
    types: [opened]

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
    - name: Transfer Issue
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GH_TOKEN}}
        script: script: |
  const issueTitle = context.payload.issue.title;
  const issueBody = context.payload.issue.body;
  const issueNumber = context.payload.issue.number;
  const organizationName = 'near';
  const projectName = 'NEAR Docs';

  // Fetch project ID and other necessary IDs
  const query = `
    query {
      organization(login: "${organization\$rg}") {
        projectV2(number: 117) {
          id
        }
      }
    }
  `;

  const projectId = await github.graphql(query);

  // Add issue to the project
  const mutation = `
    mutation($projectId: ID!, $contentId: ID!) {
      addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
        item {
          id
        }
      }
    }
  `;

  await github.graphql(mutation, { projectId: projectId.organization.projectV2.id, contentId: context.payload.issue.node_id });
